import type { Metadata } from "next";
import { Noto_Sans_Thai, Anuphan } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/sidebar";
import Topbar from "@/components/topbar";
import SettingsProvider from "@/components/setting-provider";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
});

const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSansThai.variable} ${anuphan.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="h-screen overflow-hidden flex flex-row"
      >
        <SettingsProvider>
          <Sidebar />

          <div className="flex flex-1 min-w-0 h-screen flex-col">
            <Topbar />

            <main className="flex-1 min-h-0 overflow-y-auto">{children}</main>
          </div>
        </SettingsProvider>
      </body>
    </html>
  );
}
