import type { Metadata } from "next";
import { Noto_Sans_Thai, Anuphan } from "next/font/google";
import "../globals.css";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
});

const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSansThai.variable} ${anuphan.variable} h-full antialiased`}
    >
      <body>
          <main className="flex-1 h-dvh overflow-y-auto">
            {children}
          </main>
      </body>
    </html>
  );
}
